def hanged(num):
    if num == 7:
        print("    ________|")
        print("    |      \\|")
        print("            |")
        print("            |")
        print("            |")
        print("            |")
        print(" ___________|___")
        print(" |    1/8      |")
        print(" |              |")
    elif num == 6:
        print("    ________|")
        print("    |      \\|")
        print("    O       |")
        print("            |")
        print("            |")
        print("            |")
        print(" ___________|___")
        print(" |    2/8      |")
        print(" |              |")
    elif num == 5:
        print("    ________|")
        print("    |      \\|")
        print("    O       |")
        print("    |       |")
        print("            |")
        print("            |")
        print(" ___________|___")
        print(" |    3/8      |")
        print(" |              |")
    elif num == 4:
        print("    ________|")
        print("    |      \\|")
        print("    O       |")
        print("    |       |")
        print("    |       |")
        print("            |")
        print(" ___________|___")
        print(" |    4/8      |")
        print(" |              |")
    elif num == 3:
        print("    ________|")
        print("    |      \\|")
        print("    O       |")
        print("   /|       |")
        print("    |       |")
        print("            |")
        print(" ___________|___")
        print(" |    5/8      |")
        print(" |              |")
    elif num == 2:
        print("    ________|")
        print("    |      \\|")
        print("    O       |")
        print("   /|\      |")
        print("    |       |")
        print("            |")
        print(" ___________|___")
        print(" |    6/8      |")
        print(" |              |")
    elif num == 1:
        print("    ________|")
        print("    |      \\|")
        print("    O       |")
        print("   /|\      |")
        print("    |       |")
        print("   /        |")
        print(" ___________|___")
        print(" |    7/8      |")
        print(" |              |")
    elif num == 0:
        print("    ________|")
        print("    |      \\|")
        print("    O       |")
        print("   /|\      |")
        print("    |       |")
        print("   / \      |")
        print(" ___________|___")
        print(" |    8/8      |")
        print(" |              |")
    elif num == 8:
        print("            |")
        print("            |")
        print("            |")
        print("            |")
        print("            |")
        print("            |")
        print(" ___________|___")
        print(" |    0/8      |")
        print(" |              |")
